src/api/urls.py
from django.urls import path

from api.views import (
    ImageList,
    ImageCreate,
)

app_name = "api"

urlpatterns = [
    path("images/", ImageList.as_view(), name="image-list"),
    path("images/upload/", ImageCreate.as_view(), name="image-upload"),
]

src/dashboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import path, include

from dashboard.views import (
    Dashboard,
    PostList,
    PostUpdate,
    PostDelete,
    PostCreate,
    PageList,
    PageUpdate,
    PageDelete,
    PageCreate,
    ImageList,
    ImageUpdate,
    ImageDelete,
    ImageCreate,
    GalleryList,
    GalleryUpdate,
    GalleryDelete,
    GalleryCreate,
)

app_name = "dashboard"

urlpatterns = [
    path("", Dashboard.as_view(), name="home"),
    path("posts/", PostList.as_view(), name="post-list"),
    path("posts/<int:pk>/edit", PostUpdate.as_view(), name="post-edit"),
    path("posts/<int:pk>/delete", PostDelete.as_view(), name="post-delete"),
    path("posts/create", PostCreate.as_view(), name="post-create"),
    path("pages/", PageList.as_view(), name="page-list"),
    path("pages/<int:pk>/edit", PageUpdate.as_view(), name="page-edit"),
    path("page/<int:pk>/delete", PageDelete.as_view(), name="page-delete"),
    path("pages/create", PageCreate.as_view(), name="page-create"),
    path("images/", ImageList.as_view(), name="image-list"),
    path("images/<int:pk>/edit", ImageUpdate.as_view(), name="image-edit"),
    path("images/<int:pk>/delete", ImageDelete.as_view(), name="image-delete"),
    path("images/create", ImageCreate.as_view(), name="image-create"),
    path("galleries/", GalleryList.as_view(), name="gallery-list"),
    path("galleries/<int:pk>/edit", GalleryUpdate.as_view(), name="gallery-edit"),
    path("galleries/<int:pk>/delete", GalleryDelete.as_view(), name="gallery-delete"),
    path("galleries/create", GalleryCreate.as_view(), name="gallery-create"),
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout",),
]

src/frontend/urls.py
from django.urls import path
from django.conf import settings

from frontend.views import (
    IndexView,
    PostView,
    PageView,
)


app_name = "frontend"

urlpatterns = []

# Include a image page if the feed is enabled under the specified path
# This is included first in order to allow overriding other pages
if settings.INCLUDE_IMAGE_FEED:
    from frontend.views import ImageView  # noqa

    urlpatterns += [
        path(settings.IMAGE_FEED_PATH, ImageView.as_view(), name="image-list")
    ]

urlpatterns += [
    path("", IndexView.as_view(), name="index"),
    path("<slug:slug>", PageView.as_view(), name="page-detail"),
    path("posts/<int:pk>", PostView.as_view(), name="post-detail"),
]

src/bokstaever/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from images.models import Image


class Gallery(models.Model):
    """Includes one or more images and a unique name."""

    name = models.CharField(max_length=50, unique=True, verbose_name=_("Name"))
    images = models.ManyToManyField(Image, verbose_name=_("Images"))


TEXT_CHOICES = (
    ("md", _("Markdown")),
    ("mdhtml", _("Markdown with inline HTML")),
    ("html", _("HTML")),
    ("raw", _("Raw, linebreaks are rendered")),
)


class SiteModel(models.Model):
    """Abstract model for all posts and pages."""

    image = models.ForeignKey(
        Image, on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_("Image")
    )

    text = models.TextField(verbose_name=_("Text"))
    type = models.CharField(
        max_length=6, choices=TEXT_CHOICES, default="md", verbose_name=_("Typ")
    )

    def __str__(self):
        return f"{self.headline}"

    class Meta:
        abstract = True


class Post(SiteModel):
    """Blog style articles with editors and drafts."""

    published = models.DateField(auto_now_add=True, verbose_name=_("Published"))
    editors = models.ManyToManyField(User, verbose_name=_("Editors"))
    headline = models.CharField(max_length=200, verbose_name=_("Headline"))
    draft = models.BooleanField(default=False, verbose_name=_("Draft"))

    class Meta:
        ordering = ["-published", "-pk"]


class PageManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class PageModel(models.Model):
    """Wrapper around page types."""

    objects = PageManager()

    slug = models.SlugField(max_length=200, verbose_name=_("Slug"))
    headline = models.CharField(max_length=200, verbose_name=_("Headline"))
    show_menu = models.BooleanField(default=True, verbose_name=_("Show menu"))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.headline)
        super().save(*args, **kwargs)

    def natural_key(self):
        return (self.slug,)

    def __str__(self):
        return f"{self.headline}"

    class Meta:
        unique_together = ("slug",)
        ordering = ["-pk"]


class FilePage(PageModel):
    """Page that is loaded from a file without database interaction."""

    path = models.CharField(max_length=200, verbose_name=_("Path"))


class DatabasePage(PageModel, SiteModel):
    """Normal page that get's the content from the database."""

    pass

src/dashboard/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from bokstaever.models import (
    Post,
    DatabasePage,
    Image,
    Gallery,
)

from dashboard.fields import ImageChoiceField


class PostForm(forms.ModelForm):
    image = ImageChoiceField(required=False, label=_("Image"))

    class Meta:
        model = Post
        fields = ["headline", "draft", "text", "type", "image"]


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["title", "feed"] if settings.INCLUDE_IMAGE_FEED else ["title"]

class PageForm(forms.ModelForm):
    image = ImageChoiceField(required=False, label=_("Image"))

    class Meta:
        model = DatabasePage
        fields = ["headline", "show_menu", "text", "type", "image"]


class GalleryForm(forms.ModelForm):
    images = ImageChoiceField(multiple=True, label=_("Images"))

    class Meta:
        model = Gallery
        fields = ["name", "images"]

src/dashboard/views.py
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView, FormView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Value, CharField, Count
from django.db.models.functions import TruncMonth

from collections import defaultdict

from datetime import datetime

from django.http import JsonResponse

from django_rq import get_queue

from bokstaever.models import Post, DatabasePage, FilePage, Gallery

from images.models import Image

from dashboard.forms import PostForm, PageForm, ImageForm, GalleryForm


class DeleteView(LoginRequiredMixin, DeleteView):
    def get(self, request, pk, **kwargs):
        return JsonResponse({"pk": pk}, status=200)


class Dashboard(LoginRequiredMixin, TemplateView):
    """Dashboard homepage featuring statistics about the instance."""

    template_name = "dashboard/home.html"

    def count_posts():
        """Count the published posts per month for the last 3 years."""

        def scale(value):
            if value == 1:
                return 0.4
            elif value < 3:
                return 0.7
            else:
                return 1

        post_count = Post.objects.all().count()

        ppm = (
            Post.objects.filter()
            .annotate(m=TruncMonth("published"))
            .values("m")
            .annotate(c=Count("id"))
            .order_by()
        )

        today = datetime.today()
        data = {}

        activities = defaultdict(dict)
        for a in ppm:
            activities[a["m"].year][a["m"].month] = scale(a["c"])

        for i in range(0, 3):
            year = today.year - i
            data[year] = []
            for month in range(1, 13):
                try:
                    data[year].append((month, activities[year][month]))
                except KeyError:
                    data[year].append((month, 0.1))

        return data

    def get_context_data(self, **kwargs):
        """Inject statistics."""

        context = super().get_context_data(**kwargs)

        context["statistics"] = {}
        context["statistics"]["activity"] = Dashboard.count_posts()
        return context


class DashboardListView(LoginRequiredMixin, ListView):
    paginate_by = 16


class PostList(DashboardListView):
    model = Post
    template_name = "dashboard/post_list.html"


class PostEdit(LoginRequiredMixin):
    template_name = "dashboard/post_edit.html"
    success_url = "/dashboard/posts"
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        """Adds the user as an editor of the post and saves the post."""

        self.object = form.save()
        self.object.editors.add(self.request.user)
        return super().form_valid(form)


class PostUpdate(PostEdit, UpdateView):
    pass


class PostCreate(PostEdit, CreateView):
    pass


class PostDelete(PostEdit, DeleteView):
    pass


class PageList(DashboardListView):
    template_name = "dashboard/page_list.html"

    def get_queryset(self):
        """Show database pages but also list file pages."""

        values = ["pk", "headline", "show_menu", "slug", "t"]

        db_page = (
            DatabasePage.objects.all()
            .annotate(t=Value("db", CharField()))
            .values(*values)
        )

        file_page = (
            FilePage.objects.all()
            .annotate(t=Value("file", CharField()))
            .values(*values)
        )

        data = db_page.union(file_page).order_by("t")
        return data


class PageEdit(LoginRequiredMixin):
    template_name = "dashboard/page_edit.html"
    success_url = "/dashboard/pages"
    form_class = PageForm
    model = DatabasePage


class PageUpdate(PageEdit, UpdateView):
    pass


class PageCreate(PageEdit, CreateView):
    pass


class PageDelete(PageEdit, DeleteView):
    pass

# Orderings for an imagelist
IMAGE_LIST_ORDERING = {
    "desc": "-creation_date",
    "asc": "creation_date",
    "new": "-pk"
}

class ImageList(DashboardListView):
    paginate_by = 36

    template_name = "dashboard/image_list.html"
    ordering = "-creation_date"
    queryset = Image.objects.filter(thumbnail__isnull=False)

    def get_ordering(self):
        """Returns default ordering or value defined on
        the ordering GET parameter.
        """

        if order := self.request.GET.get("ordering"):
            try:
                return IMAGE_LIST_ORDERING[order]
            except KeyError:
                pass
        return self.ordering

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        queue = get_queue("default")
        count = len(queue.jobs) + queue.started_job_registry.count

        context["processing_count"] = count
        context["is_processing"] = count > 0

        return context


class ImageUpdate(LoginRequiredMixin, UpdateView):
    template_name = "dashboard/image_edit.html"
    success_url = "/dashboard/images"
    model = Image
    form_class = ImageForm


class ImageCreate(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/image_create.html"


class ImageDelete(DeleteView):
    success_url = "/dashboard/images"
    model = Image


class GalleryList(DashboardListView):
    template_name = "dashboard/gallery_list.html"
    ordering = ["-id"]
    model = Gallery


class GalleryEdit(LoginRequiredMixin):
    template_name = "dashboard/gallery_edit.html"
    success_url = "/dashboard/galleries"
    form_class = GalleryForm
    model = Gallery


class GalleryCreate(GalleryEdit, CreateView):
    pass


class GalleryDelete(GalleryEdit, DeleteView):
    pass


class GalleryUpdate(GalleryEdit, UpdateView):
    pass

src/dashboard/templates/dashboard/base.html
{% load static %}
{% load i18n %}

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/extern/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">

    <title>Dashboard - {% block title %}bokstaever{% endblock title %}</title>

    <script src="{% static 'dashboard/extern/js/bootstrap.min.js' %}"></script>

    {% block header %}
    {% endblock header %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            {% trans "Dashboard" as title %}
            {% include "dashboard/snippets/navigation.html" with name="dashboard:home" %}
            {% trans "Posts" as title %}
            {% include "dashboard/snippets/navigation.html" with name="dashboard:post-list" %}
            {% trans "Pages" as title %}
            {% include "dashboard/snippets/navigation.html" with name="dashboard:page-list" %}
            {% trans "Images" as title %}
            {% include "dashboard/snippets/navigation.html" with name="dashboard:image-list" %}
            {% trans "Galleries" as title %}
            {% include "dashboard/snippets/navigation.html" with name="dashboard:gallery-list" %}
          </ul>
        </div>
        {% if request.user.is_authenticated %}
          <ul class="navbar-nav d-flex">
            <li class="nav-item">
              {% spaceless %}
              <a class="nav-link" href="{% url "dashboard:logout" %}">
                {% trans "Hello, " %}
                {% firstof request.user.first_name request.user.username %}
                {% trans " (logout)" %}
              </a>
              {% endspaceless %}
            </li>
          </ul>
        {% endif %}
      </div>
    </nav>

    <div class="content container mb-2 mt-2 clearfix">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

src/dashboard/templates/dashboard/gallery_edit.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Edit gallery" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Edit gallery" %}</h1>
  {% include "dashboard/snippets/forms.html" %}
  {% blocktrans asvar warning %}
    You're about to delete this gallery. It could be used on some post or page. Please be careful.
  {% endblocktrans %}
  {% include "dashboard/snippets/delete_confirm.html" with view="dashboard:gallery-delete" %}
{% endblock content %}

src/dashboard/templates/dashboard/gallery_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Galleries" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Galleries" %}</h1>
  <p>
    <a href="{% url "dashboard:gallery-create" %}">{% trans "Create new gallery" %}</a>
  </p>

  {% if object_list %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">{% trans "ID" %}</th>
          <th scope="col">{% trans "Name" %}</th>
          <th scope="col">{% trans "Actions" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for gallery in object_list %}
        <tr>
          <td>{{ gallery.pk }}</td>
          <td>{{ gallery.name }}</td>
          <td><a href="{% url "dashboard:gallery-edit" gallery.pk %}">{% trans "Edit" %}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    {% trans "No pages" %}
  {% endif %}

  {% include "dashboard/snippets/pagination.html" %}
{% endblock content %}

src/dashboard/templates/dashboard/home.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}{% trans "Home" %}{% endblock title %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/home.css' %}">
{% endblock header %}

{% block content %}
<div class="row justify-content-center">
  {% for year, months in statistics.activity.items reversed %}
    <div class="year">
      <div class="description">{{ year }}</div>
      <div class="months">
      {% for month in months %}
          <svg
            class="month"
            height="10"
            width="10"
            style="opacity: {{ month.1|unlocalize }}"
          >
            <rect
              x="0"
              y="0"
              width="10"
              height="10"
              style="fill: {% if month.1 != 0.1 %}green{% else %}black{% endif %}"
            />
          </svg>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}

src/dashboard/templates/dashboard/image_create.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Upload images" %}{% endblock title %}

{% block header %}
    <script src="{% static "dashboard/js/image_upload.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "dashboard/css/image_upload.css" %}">
{% endblock header %}

{% block content %}
  <h1>{% trans "Upload images" %}</h1>

  <!-- Shows alerts on upload errors -->
  <div id="alertAnchor"></div>
  <!-- This form is never submitted, upload happens via js -->
  <form id="imageUpload">
    {% csrf_token %}

    <input autocomplete="off" class="form-control" type="file" id="imageInput" accept="image/*" multiple>

    <!-- Used for displaying images selected via the input above -->
    <div id="anchor" class="images"></div>

    <button id="trigger" type="button" class="btn btn-primary float-end">{% trans "Upload" %}</button>
  </form>

  <script>
    const imageUpload = new ImageUpload("{% url "api:image-upload" %}")
    imageUpload.updateImages()
  </script>
{% endblock content %}

src/dashboard/templates/dashboard/image_edit.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Edit Image" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Edit Image" %}</h1>
  <div class="row justify-content-center">
    <div class="col-10 col-md-5 col-lg-4 col-xl-3">
      <div class="card">
        <img class="card-img-top" src="{{ image.thumbnail.image_file.url }}">
        <div class="card-body">
          <p class="card-text"><small class="text-muted">{% trans "Creation date:" %} {{ image.creation_date }}</small></p>
          {% include "dashboard/snippets/forms.html" with simple=True %}

          {% blocktrans with post_count=object.post_set.count page_count=object.databasepage_set.count gallery_count=object.gallery_set.count asvar warning %}
            You're about to delete this image. It will be removed from all galleries, posts and pages using it. Currently used by:
            <ul>
              <li>Posts: {{ post_count }}</li>
              <li>Pages: {{ page_count }}</li>
              <li>Galleries: {{ gallery_count }}</li>
            </ul>
          {% endblocktrans %}
          {% include "dashboard/snippets/delete_confirm.html" with view="dashboard:image-delete" %}
          <a href="{{ image.files.last.image_file.url }}">{% trans "View" %}</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

src/dashboard/templates/dashboard/image_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Image list" %}{% endblock title %}

{% block content %}
  <!-- Warns if there are unprocessed images -->
  {% if is_processing %}
  <div class="alert alert-warning" role="alert">
    {% blocktrans count c=processing_count %}
      One image is still processing in the background.
      {% plural %}
      {{ c }} images are still processing in the background. They show up once there finished.
    {% endblocktrans %}
  </div>
  {% endif %}

  <h1>{% trans "Images" %}</h1>

  <div class="list-options">
    <form class="form-inline">
      <label for="ordering">{% trans "Ordering" %}</label>
      <select id="ordering" name="ordering" class="form-control" onchange="this.form.submit()">
        <option value="desc" {% if request.GET.ordering == "desc"  or not request.GET.ordering %}selected{% endif %}>
          {% trans "Creation Date - Descending" %}
        </option>
        <option value="asc" {% if request.GET.ordering == "asc" %}selected{% endif %}>
          {% trans "Creation Date - Ascending" %}
        </option>
        <option value="new" {% if request.GET.ordering == "new" %}selected{% endif %}>
          {% trans "Upload Date - Descending" %}
        </option>
      </select>
      <noscript>
        <input class="btn btn-primary" type="submit" value="{% trans "Submit" %}">
      </noscript>
    </form>
  </div>

  <p><a href="{% url "dashboard:image-create" %}">{% trans "Create image" %}</a></p>

  {% if object_list %}
    <div class="images">
      <div class="row">
        {% for image in object_list %}
          <div class="col-6 col-sm-4 col-md-3 col-lg-2">
            <a href="{% url "dashboard:image-edit" image.pk %}">
              <img class="img-thumbnail fixed-size" src="{{ image.thumbnail.image_file.url }}">
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  {% else %}
    {% trans "No images." %}
  {% endif %}

  {% include "dashboard/snippets/pagination.html" %}
{% endblock content %}

src/dashboard/templates/dashboard/page_edit.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Edit Page" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Edit Page" %}</h1>
  {% include "dashboard/snippets/forms.html" %}

  {% trans "You're about to delete this page." as warning %}
  {% include "dashboard/snippets/delete_confirm.html" with view="dashboard:page-delete" %}
{% endblock content %}

src/dashboard/templates/dashboard/page_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Pages" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Pages" %}</h1>
  <p>
    <a href="{% url "dashboard:page-create" %}">{% trans "Create new page" %}</a>
  </p>

  {% if object_list %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">{% trans "ID" %}</th>
          <th scope="col">{% trans "Headline" %}</th>
          <th scope="col">{% trans "In menu" %}</th>
          <th scope="col">{% trans "Actions" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for page in object_list %}
        <tr>
          <td>{{ page.pk }}</td>
          <td>{{ page.headline }}</td>
          <td>{{ page.show_menu }}</td>
          <td>
            <a href="{% url "frontend:page-detail" page.slug %}">{% trans "Link" %}</a>
            {% if page.t == "db" %}
            <a href="{% url "dashboard:page-edit" page.pk %}">{% trans "Edit" %}</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    {% trans "No pages" %}
  {% endif %}

  {% include "dashboard/snippets/pagination.html" %}
{% endblock content %}

src/dashboard/templates/dashboard/post_edit.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Edit Post" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Edit Post" %}</h1>
  {% include "dashboard/snippets/forms.html" %}
  {% trans "You're about to delete this post." as warning %}
  {% include "dashboard/snippets/delete_confirm.html" with view="dashboard:post-delete" %}
{% endblock content %}

src/dashboard/templates/dashboard/post_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Posts" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Posts" %}</h1>
  <p>
    <a href="{% url "dashboard:post-create" %}">{% trans "Create new post" %}</a>
  </p>

  {% if object_list %}
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">{% trans "ID" %}</th>
            <th scope="col">{% trans "Headline" %}</th>
            <th scope="col">{% trans "Authors" %}</th>
            <th scope="col">{% trans "Creation date" %}</th>
            <th scope="col">{% trans "Actions" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for post in object_list %}
              <tr>
                <td>{{ post.pk }}</td>
                <td>{{ post.headline }}</td>
                <td>
                  {% spaceless %}
                    {% for editor in post.editors.all %}
                      {% firstof editor.first_name editor.username %}
                      {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  {% endspaceless %}
                </td>
                <td>{{ post.published }}</td>
                <td>
                  <a href="{% url "dashboard:post-edit" post.pk %}">{% trans "Edit" %}</a>
                </td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    {% trans "No posts" %}
  {% endif %}

  {% include "dashboard/snippets/pagination.html" %}
{% endblock content %}